name: auth
description: Auth service
version: 1.0.1


environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  conduit: 4.3.9
  conduit_core: 4.3.8
  conduit_postgresql: ^4.3.0
  jaguar_jwt: 3.0.0
  


dev_dependencies:
  lints: ^2.0.1
  
